# fly.toml app configuration file generated for reaction on 2025-11-12T20:10:59+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reaction'
primary_region = 'nrt'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
